# Generated by Django 6.0.5 on 2026-05-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationState',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_tick', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
