# Generated by Django 6.0.5 on 2026-05-09 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_simulationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polygon', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('geofence', 'geofence'), ('proximity', 'proximity'), ('system', 'system')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('critical', 'critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.ship')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.restrictedzone')),
            ],
        ),
    ]
