# Generated by Django 6.0.5 on 2026-05-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_restrictedzone_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('geofence', 'geofence'), ('proximity', 'proximity'), ('distress', 'distress'), ('system', 'system')], max_length=20),
        ),
    ]
