# Generated by Django 6.0.5 on 2026-05-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alert_details_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='assigned_captain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ShipSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('heading', models.IntegerField()),
                ('fuel', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.ship')),
            ],
            options={
                'indexes': [models.Index(fields=['ship', 'created_at'], name='fleet_ships_ship_id_2f72ec_idx')],
            },
        ),
    ]
